### ISSUE TITLE
Not able to compile this contract

### ISSUE THREAD

**Issue by umarislam2** [0xmetaschool/Q-boilerplate-code#3]
Hi while taking the DAO tutorial for Q block chain I have encountered the below errors when compiling this contract, please have a look and help in resolving these issues.
DeclarationError: Identifier not found or not unique.
  --> contracts/GeneralDAOVoting.sol:23:42:
   |
23 | contract GeneralDAOVoting is IDAOVoting, Initializable, AbstractDependant {
   |                                          ^^^^^^^^^^^^^

Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (D:\hardhat-tutorial\node_modules\hardhat\src\builtin-tasks\compile.ts:503:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at OverriddenTaskDefinition._action (D:\hardhat-tutorial\node_modules\@typechain\hardhat\src\index.ts:28:30)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment.run (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)
    at SimpleTaskDefinition.action (D:\hardhat-tutorial\node_modules\hardhat\src\builtin-tasks\compile.ts:1381:63)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment.run (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)

This one can be resolved by importing this contract "@openzeppelin/contracts/proxy/utils/Initializable.sol" but then I run into the below error

 npx hardhat run scripts/AirDropV2/2_createVoting.js --network testnet --show-stack-traces
DeclarationError: Identifier not found or not unique.
  --> contracts/GeneralDAOVoting.sol:20:57:
   |
20 | contract GeneralDAOVoting is IDAOVoting, Initializable, AbstractDependant {
   |                                                         ^^^^^^^^^^^^^^^^^

Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (D:\hardhat-tutorial\node_modules\hardhat\src\builtin-tasks\compile.ts:503:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at OverriddenTaskDefinition._action (D:\hardhat-tutorial\node_modules\@typechain\hardhat\src\index.ts:28:30)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment.run (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)
    at SimpleTaskDefinition.action (D:\hardhat-tutorial\node_modules\hardhat\src\builtin-tasks\compile.ts:1381:63)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment.run (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)

**Comment by umarislam2** [comment]
As an update I was able to reach this point only after removing few of the packages as I was getting the below issues earlier, these are 

import "@q-dev/gdk-contracts/interfaces/IDAOVoting.sol";
import "@q-dev/gdk-contracts/DAO/DAOVault.sol";
import "@q-dev/gdk-contracts/DAO/DAORegistry.sol";
import "@q-dev/gdk-contracts/DAO/PermissionManager.sol";
import "@q-dev/gdk-contracts/DAO/DAOParameterStorage.sol";
import "@q-dev/gdk-contracts/libs/Parameters.sol";

The errors that I got were as below when I run this script
npx hardhat run scripts/AirDropV2/2_createVoting.js --network testnet --show-stack-traces

λ npx hardhat run scripts/AirDropV2/2_createVoting.js --network testnet --show-stack-traces
DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:12:1:
   |
12 | import "@q-dev/gdk-contracts/DAO/DAOVault.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:5:1:
  |
5 | uint256 constant DECIMAL = 10 ** 18;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:12:1:
   |
12 | import "@q-dev/gdk-contracts/DAO/DAOVault.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> @openzeppelin/contracts/proxy/utils/Initializable.sol:58:1:
   |
58 | abstract contract Initializable {
   | ^ (Relevant source part starts here and spans across multiple lines).


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:12:1:
   |
12 | import "@q-dev/gdk-contracts/DAO/DAOVault.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:6:1:
  |
6 | uint256 constant PERCENTAGE_100 = 10 ** 27;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:12:1:
   |
12 | import "@q-dev/gdk-contracts/DAO/DAOVault.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:4:1:
  |
4 | uint256 constant PRECISION = 10 ** 25;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:12:1:
   |
12 | import "@q-dev/gdk-contracts/DAO/DAOVault.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> @dlsl/dev-modules/libs/data-structures/StringSet.sol:13:1:
   |
13 | library StringSet {
   | ^ (Relevant source part starts here and spans across multiple lines).


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:13:1:
   |
13 | import "@q-dev/gdk-contracts/DAO/DAORegistry.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:5:1:
  |
5 | uint256 constant DECIMAL = 10 ** 18;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:13:1:
   |
13 | import "@q-dev/gdk-contracts/DAO/DAORegistry.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> @openzeppelin/contracts/proxy/utils/Initializable.sol:58:1:
   |
58 | abstract contract Initializable {
   | ^ (Relevant source part starts here and spans across multiple lines).


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:13:1:
   |
13 | import "@q-dev/gdk-contracts/DAO/DAORegistry.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:6:1:
  |
6 | uint256 constant PERCENTAGE_100 = 10 ** 27;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:13:1:
   |
13 | import "@q-dev/gdk-contracts/DAO/DAORegistry.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:4:1:
  |
4 | uint256 constant PRECISION = 10 ** 25;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:13:1:
   |
13 | import "@q-dev/gdk-contracts/DAO/DAORegistry.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> @dlsl/dev-modules/libs/data-structures/StringSet.sol:13:1:
   |
13 | library StringSet {
   | ^ (Relevant source part starts here and spans across multiple lines).


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:14:1:
   |
14 | import "@q-dev/gdk-contracts/DAO/PermissionManager.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:5:1:
  |
5 | uint256 constant DECIMAL = 10 ** 18;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:14:1:
   |
14 | import "@q-dev/gdk-contracts/DAO/PermissionManager.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> @openzeppelin/contracts/proxy/utils/Initializable.sol:58:1:
   |
58 | abstract contract Initializable {
   | ^ (Relevant source part starts here and spans across multiple lines).


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:14:1:
   |
14 | import "@q-dev/gdk-contracts/DAO/PermissionManager.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:6:1:
  |
6 | uint256 constant PERCENTAGE_100 = 10 ** 27;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:14:1:
   |
14 | import "@q-dev/gdk-contracts/DAO/PermissionManager.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:4:1:
  |
4 | uint256 constant PRECISION = 10 ** 25;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:14:1:
   |
14 | import "@q-dev/gdk-contracts/DAO/PermissionManager.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> @dlsl/dev-modules/libs/data-structures/StringSet.sol:13:1:
   |
13 | library StringSet {
   | ^ (Relevant source part starts here and spans across multiple lines).


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:15:1:
   |
15 | import "@q-dev/gdk-contracts/DAO/DAOParameterStorage.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:5:1:
  |
5 | uint256 constant DECIMAL = 10 ** 18;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:15:1:
   |
15 | import "@q-dev/gdk-contracts/DAO/DAOParameterStorage.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> @openzeppelin/contracts/proxy/utils/Initializable.sol:58:1:
   |
58 | abstract contract Initializable {
   | ^ (Relevant source part starts here and spans across multiple lines).


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:15:1:
   |
15 | import "@q-dev/gdk-contracts/DAO/DAOParameterStorage.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:6:1:
  |
6 | uint256 constant PERCENTAGE_100 = 10 ** 27;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:15:1:
   |
15 | import "@q-dev/gdk-contracts/DAO/DAOParameterStorage.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> @dlsl/dev-modules/utils/Globals.sol:4:1:
  |
4 | uint256 constant PRECISION = 10 ** 25;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


DeclarationError: Identifier already declared.
  --> contracts/GeneralDAOVoting.sol:15:1:
   |
15 | import "@q-dev/gdk-contracts/DAO/DAOParameterStorage.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> @dlsl/dev-modules/libs/data-structures/StringSet.sol:13:1:
   |
13 | library StringSet {
   | ^ (Relevant source part starts here and spans across multiple lines).


Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (D:\hardhat-tutorial\node_modules\hardhat\src\builtin-tasks\compile.ts:503:15)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at OverriddenTaskDefinition._action (D:\hardhat-tutorial\node_modules\@typechain\hardhat\src\index.ts:28:30)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment.run (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)
    at SimpleTaskDefinition.action (D:\hardhat-tutorial\node_modules\hardhat\src\builtin-tasks\compile.ts:1381:63)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment._runTaskDefinition (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment.run (D:\hardhat-tutorial\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)
    at SimpleTaskDefinition.action (D:\hardhat-tutorial\node_modules\hardhat\src\builtin-tasks\compile.ts:1461:7)
